import type {AppProps} from 'next/app';
import Head from 'next/head';
import Script from 'next/script'
import 'tailwindcss/tailwind.css';
import '../styles/globals.css'

function MyApp({Component, pageProps}: AppProps) {
  return (
    <>
      <Script src="https://kit.fontawesome.com/b9663aed1f.js" crossOrigin="anonymous"></Script>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
export default MyApp;
